# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20160311_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='views',
            new_name='catviews',
        ),
    ]
